# Clippy configuration for P2P Foundation - Simplified for CI
# Allow unwrap in tests only
allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-panic-in-tests = true

# Basic thresholds
cognitive-complexity-threshold = 30
too-many-arguments-threshold = 10
type-complexity-threshold = 250